title: FarmBot Business Documentation
url: https://meta.farm.bot
description: Open documentation for the way we do business
logo: /assets/images/documentation.png
remote_theme: FarmBot-Docs/farmbot-theme@main
baseurl: /
color: '#434343'
latest_version_number: 2021
plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag
include:
  - _images
  - _redirects
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor
algolia:
  application_id: Z1MM044EZ8
  index_name: meta
  search_only_api_key: cad8ec927860485f3a8ac1ce2372be28
  nodes_to_index: 'p,table,h1'
  files_to_exclude:
    - index.md
    - v2020/**/*
