title: FarmBot Business Documentation
url: https://meta.farm.bot
description: Open documentation for the way we do business
logo: /assets/images/documentation.png
theme: jekyll-theme-cayman
remote_theme: FarmBot-Docs/farmbot-theme@main
baseurl: /
color: '#434343'
latest_version_number: 2021
plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-remote-theme
include:
  - _images
  - _redirects
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor
